### PR TITLE
zz

### PR DESCRIPTION
**Pull request by shogunator1337**
kind of first aid versus dis evil chinese bot-net

### CODE REVIEW

**Comment by collinxchu** [comment]
Seems good and efficient for what it's trying to do. Will check with administration to see if this is something we want. Once confirmation is given, will merge.

**Comment by shogunator1337** [comment]
first 3 commits is a shit tbh but "improve" and "fix[3]" should prevent this spam brilliantly.

**Comment by shogunator1337** [comment]
well dat's cute but it doesn't work :^)

**Comment by collinxchu** [comment]
Wahey.

**Comment by shogunator1337** [comment]
well, now u can check this out

it was a surprise for me that u can't close a sockettransport in process of opening it, i bet it's surprise for u too :^)

**Comment by shogunator1337** [comment]
Hey?...

**Comment by collinxchu** [comment]
Can't actually identify anything wrong so time to merge and test the absolute piss out of it.

**Pull request merged**
